### ISSUE TITLE
anchr.io blocked because "Malware Domain"

### ISSUE THREAD

**Issue by kolaente** [n1try/anchr#1]
When i try to open anchr.io with ublockOrigin in chrome, it loads only the HTML, all JS and CSS are blocked. When i look it up in ublockOrigin's console, it says "Domain `||anchr.io^` found in https://www.malwaredomains.com/" therefore i can't open it (it works with deactivated ublockOrigin though)

As this is probably not expected behavior, someone has probably hacked your site and distributed (or is distributing) malware within...

**Comment by n1try** [comment]
Yes I know. Before I had a script to check all shortlinks against an anti-malware service someone used the shortlink service to create a link to a phishing site. But I don't know how to get removed from that blacklist again. Any ideas?

**Comment by kolaente** [comment]
Maybe use a captcha to prevent bots from shortening malware-links (I had that issue whith a site of mine) - at least for non-loggedin users. (With an option to disable it in config?)
You could also filter the sites with a blacklist or so to prevent phishing (if you're not already doing this).
Did you already contact them?
Also: http://www.malwaredomains.com/?p=212

I've found the list: https://mirror1.malwaredomains.com/files/domains.txt (don't know if that helps ^^)

**Comment by n1try** [comment]
I've already integrated https://developers.google.com/safe-browsing/ as a script running at fixed intervals and removing evil links. I plan to integrate it directly when a new link is added. I'm gonna try contacting https://openphish.com/ to get removed.

**Comment by n1try** [comment]
Is this still an issue?

**Comment by n1try** [comment]
Looks like this is not an issue anymore. I'm going to close this.
